# LINT.IfChange
from typing import Any, List, Optional, Sequence, Tuple

import numpy as np

class ItemSelector: ...

class PrioritizedSelector(ItemSelector):
    def __init__(self, priority_exponent: float): ...

class FifoSelector(ItemSelector):
    def __init__(self): ...

class LifoSelector(ItemSelector):
    def __init__(self): ...

class UniformSelector(ItemSelector):
    def __init__(self): ...

class HeapSelector(ItemSelector):
    def __init__(self, min_heap: bool): ...

def selector_from_proto(options: bytes): ...

class TableExtension: ...

class RateLimiter:
    def __init__(
        self,
        samples_per_insert: float,
        min_size_to_sample: int,
        min_diff: float,
        max_diff: float,
    ): ...

class Table:
    def __init__(
        self,
        name: str,
        sampler: ItemSelector,
        remover: ItemSelector,
        max_size: int,
        max_times_sampled: int,
        rate_limiter: RateLimiter,
        extensions: Sequence[TableExtension],
        signature: Optional[str],
    ): ...
    def name(self) -> str: ...
    def can_sample(self, num_samples: int) -> bool: ...
    def can_insert(self, num_inserts: int) -> bool: ...
    def info(self) -> bytes: ...

class Sampler:
    NUM_INFO_TENSORS: int

    def GetNextTrajectory(self) -> List[np.ndarray]: ...

class Writer:
    def Append(self, data: Sequence[np.ndarray]): ...
    def AppendSequence(self, sequence: Sequence[np.ndarray]): ...
    def CreateItem(self, table: str, num_timesteps: int, priority: float): ...
    def Flush(self): ...
    def Close(self, retry_on_unavailable: bool = ...): ...

class Client:
    def __init__(self, server_name: str): ...
    def NewWriter(
        self,
        chunk_length: int,
        max_timesteps: int,
        delta_encoded: bool = ...,
        max_in_flight_items: int = ...,
    ) -> Writer: ...
    def NewSampler(self, table: str, max_samples: int, buffer_size: int) -> Sampler: ...
    def NewTrajectoryWriter(
        self, chunker_options: ChunkerOptions, validate_items: bool
    ) -> TrajectoryWriter: ...
    def NewStructuredWriter(
        self, serialized_configs: Sequence[bytes]
    ) -> StructuredWriter: ...
    def mutate_priorities(
        self, table: str, updates: Sequence[Tuple[int, float]], deletes: Sequence[int]
    ): ...
    def Reset(self, table: str): ...
    def ServerInfo(self, timeout_sec: int) -> Sequence[bytes]: ...
    def Checkpoint(self) -> str: ...

class Checkpointer: ...

def create_default_checkpointer(
    name: str, group: str, fallback_checkpoint_path: Optional[str]
) -> Checkpointer: ...

class Server:
    def __init__(
        self,
        priority_tables: Sequence[Table],
        port: int,
        checkpointer: Optional[Checkpointer],
    ): ...
    def Stop(self): ...
    def Wait(self): ...

class WeakCellRef:
    def numpy(self) -> np.ndarray: ...
    @property
    def shape(self) -> List[Optional[int]]: ...
    @property
    def dtype(self) -> np.dtype: ...
    @property
    def expired(self) -> bool: ...

class ChunkerOptions: ...

class ConstantChunkerOptions(ChunkerOptions):
    def __init__(self, max_chunk_length: int, num_keep_alive_refs: int): ...

class AutoTunedChunkerOptions:
    def __init__(self, num_keep_alive_refs: int, throughput_weight: float): ...

class TrajectoryWriter:
    def Append(self, data: Sequence[Optional[Any]]) -> List[Optional[WeakCellRef]]: ...
    def AppendPartial(
        self, data: Sequence[Optional[Any]]
    ) -> List[Optional[WeakCellRef]]: ...
    def CreateItem(
        self,
        table: str,
        priority: float,
        py_trajectory: Sequence[Sequence[WeakCellRef]],
        squeeze_column: Sequence[bool],
    ): ...
    def Flush(self, ignore_last_num_items: int, timeout_ms: int): ...
    def EndEpisode(self, clear_buffers: bool, timeout_ms: Optional[int]): ...
    def Close(self): ...
    def ConfigureChunker(self, column: int, options: ChunkerOptions): ...
    @property
    def max_num_keep_alive_refs(self) -> int: ...
    @property
    def episode_steps(self) -> int: ...

# The gRPC-backed `Client`/`Writer` bindings are defined above (see
# `Client`/`Writer` classes). `InProcessClient` is the embedded / numpy-only
# client for `Server(in_process=True)`.
class InProcessClient:
    def __init__(
        self, tables: Sequence[Table], checkpointer: Optional[Checkpointer] = ...
    ): ...
    def new_trajectory_writer(
        self, chunker_options: ChunkerOptions
    ) -> TrajectoryWriter: ...
    def NewTrajectoryWriter(
        self, chunker_options: ChunkerOptions
    ) -> TrajectoryWriter: ...
    def new_writer(
        self,
        chunk_length: int,
        max_timesteps: int,
        delta_encoded: bool = ...,
        max_in_flight_items: int = ...,
    ) -> Writer: ...
    def NewWriter(
        self,
        chunk_length: int,
        max_timesteps: int,
        delta_encoded: bool = ...,
        max_in_flight_items: int = ...,
    ) -> Writer: ...
    def new_sampler(
        self,
        table: str,
        max_samples: int = ...,
        buffer_size: int = ...,
        rate_limiter_timeout_ms: int = ...,
    ) -> Sampler: ...
    def NewSampler(
        self,
        table: str,
        max_samples: int = ...,
        buffer_size: int = ...,
        rate_limiter_timeout_ms: int = ...,
    ) -> Sampler: ...
    def mutate_priorities(
        self, table: str, updates: Sequence[Tuple[int, float]], deletes: Sequence[int]
    ): ...
    def MutatePriorities(
        self, table: str, updates: Sequence[Tuple[int, float]], deletes: Sequence[int]
    ): ...
    def reset(self, table: str): ...
    def Reset(self, table: str): ...
    def checkpoint(self) -> str: ...
    def Checkpoint(self) -> str: ...
    def new_structured_writer(self, configs: Sequence[bytes]) -> StructuredWriter: ...
    def NewStructuredWriter(self, configs: Sequence[bytes]) -> StructuredWriter: ...
    def load_latest(self) -> None: ...
    def load(self, path: str) -> None: ...
    def server_info(self) -> Sequence[bytes]: ...
    def ServerInfo(self) -> Sequence[bytes]: ...

# ---- SHM transport (ticket ⑤) ----
# Mirrors InProcessClient's dual PascalCase/snake_case naming (R13). The
# TrajectoryWriter/StructuredWriter returned are the same C++ types as the
# gRPC/local paths, so no separate binding is needed.
class ShmSampler:
    NUM_INFO_TENSORS: int

    def GetNextTrajectory(self) -> List[np.ndarray]: ...
    def Close(self) -> None: ...

class ShmClient:
    def __init__(self, socket_path: str): ...
    @staticmethod
    def Connect(socket_path: str) -> ShmClient: ...
    def new_sampler(
        self,
        table: str,
        max_samples: int = ...,
        buffer_size: int = ...,
        rate_limiter_timeout_ms: int = ...,
    ) -> ShmSampler: ...
    def NewSampler(
        self,
        table: str,
        max_samples: int = ...,
        buffer_size: int = ...,
        rate_limiter_timeout_ms: int = ...,
    ) -> ShmSampler: ...
    def new_trajectory_writer(
        self, chunker_options: ChunkerOptions
    ) -> TrajectoryWriter: ...
    def NewTrajectoryWriter(
        self, chunker_options: ChunkerOptions
    ) -> TrajectoryWriter: ...
    def new_structured_writer(self, configs: Sequence[bytes]) -> StructuredWriter: ...
    def NewStructuredWriter(self, configs: Sequence[bytes]) -> StructuredWriter: ...

class ShmServer:
    def __init__(self, table: Table, socket_path: str = ...): ...
    @staticmethod
    def Create(table: Table, socket_path: str = ...) -> ShmServer: ...
    def Start(self) -> None: ...
    def Stop(self) -> None: ...
    @property
    def socket_path(self) -> str: ...

# LINT.ThenChange(pybind.cc)
