# Description: Example notebooks (numpy, in-process Reverb usage).

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

exports_files([
    "demo.ipynb",
    "frame_stacking.ipynb",
])
