# Description: Example scripts and notebooks (numpy, Reverb usage).

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

exports_files([
    "demo.ipynb",
    "frame_stacking.ipynb",
    "grpc_client.py",
    "shm_client.py",
    "structured_writer.py",
])
