# Description: Example scripts and notebooks (numpy, Reverb usage).

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

exports_files([
    "demo.ipynb",
    "frame_stacking.ipynb",
    "grpc_client.py",
    "shm_client.py",
    "structured_writer.py",
    "demo.py",
    "training_loop.py",
    "production_patterns.py",
    "structured_writer_advanced.py",
    "table_signature.py",
    "multi_server.py",
])
